version: 3
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
  backend:
    image: pavan5883/backend:1.0.0
    ports:
      - 5000:5000
  frontend:
    image: pavan5883/frontend:1.0.0
    ports:
      - 3000:3000