version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
  backend:
    image: pavan5883/back-end:1.0.1
    ports:
      - 5000:5000
    depends_on:
      - mongodb
  frontend:
    image: pavan5883/front-end:1.0.3
    ports:
      - 3000:3000
    depends_on:
      - backend